groups:
    - bash
    - developer
    - smartie
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - applications::dropbox
        - applications::omnigraffle
        - applications::vlc
        - sudo::default
        - applications::vagrant
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::set_computer_name
attributes:
    git:
        name: Kim Ausloos 
        email: kim.ausloos@kunstmaan.be
    osxdefaults:
        computername: voyager2
    authorization:
        sudo:
            users:
                - kim
            passwordless: true
            include_sudoers_d: true
